default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  localhost: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: 'postgresql://postgres@localhost/auth-test-dev-db'

test:
  <<: *default
  url: 'postgresql://postgres@localhost/auth-test-test-db'

production:
  <<: *default
  url: <%= ENV['AUTH_TEST_DATABASE_PRODUCTION_URL'] %>
  username: <%= ENV['AUTH_TEST_DATABASE_PRODUCTION_USERNAME'] %>
  password: <%= ENV['AUTH_TEST_DATABASE_PRODUCTION_PASSWORD'] %>
